### ISSUE TITLE
adding real-time database Authentication

### ISSUE THREAD

**Issue by Rup-Royofficial** [saikishan5000/renttire#11]
Database authentication for user login and user registration using real-time database integration. This would insert or can retrieve the user credentials as needed.

I will be working on developing this either along with the signup page or immediately after the development of the signup page

Consider assigning me this issue!

**Comment by saikishan5000** [comment]
assigned

**Comment by Rup-Royofficial** [comment]
This issue has been dealt with

**Comment by Rup-Royofficial** [comment]
Btw you may add the enhancement label to this issue!
