### ISSUE TITLE
Adding a Signup page

### ISSUE THREAD

**Issue by Rup-Royofficial** [saikishan5000/renttire#4]
As stated in the layout.md #3 
I have started creating a basic sign-up page for the website
It will contain the following :

- Username entry
- Email entry
- password entry
- confirm password entry
- Containing link to sign-in page (if the user already has an account )

I have almost finished the sign-up page after which I will work on the sign-in page
Consider assigning me this

**Comment by saikishan5000** [comment]
You wrote " I have started creating a basic sign-up page for the website"    
but we are developing an app not a website, did you mean app?

**Comment by Rup-Royofficial** [comment]
I am sorry,
I started working on it thinking it to be a website

I will  rectify and start working on the sign-in/sign-up activity within the app
It will contain the following :

- Username entry
- Email entry
- password entry
- confirm password entry
- Containing link to sign-in page (if the user already has an account )

Consider assigning me this!

**Comment by saikishan5000** [comment]
Assigned.

**Comment by saikishan5000** [comment]
View this file for reference for UI of SIGN UP &SIGN IN pages [figma](https://www.figma.com/file/NHBugUCMV26AYGCrZoDEwR/SIGN-UP-%26-SIGN-IN?t=s4jnVBQ8rM6sA6JL-1).

**Comment by Rup-Royofficial** [comment]
OK

**Comment by Rup-Royofficial** [comment]
Btw you may add the enhancement label to this issue!
